CREATE TABLE "DIALOGO" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "personaje" INTEGER, "etapa" INTEGER, "texto" VARCHAR);
CREATE TABLE "ETAPA" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "mision" INTEGER, "orden" INTEGER, "texto" VARCHAR);
CREATE TABLE "MAPA" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "imagen" VARCHAR NOT NULL  UNIQUE );
CREATE TABLE "MISION" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "nombre" VARCHAR);
CREATE TABLE "NEXO" ("id" VARCHAR PRIMARY KEY  NOT NULL ,"mapa" INTEGER NOT NULL ,"posx" INTEGER NOT NULL ,"posy" INTEGER NOT NULL, "direccion" INTEGER NOT NULL ,"enlace" VARCHAR NOT NULL);
CREATE TABLE "OBSTACULO" ("id" INTEGER PRIMARY KEY  NOT NULL ,"mapa" INTEGER,"posx" INTEGER NOT NULL ,"posy" INTEGER NOT NULL ,"ancho" INTEGER NOT NULL ,"alto" INTEGER NOT NULL );
CREATE TABLE "PDINAMICO" ("id" INTEGER PRIMARY KEY  NOT NULL ,"imagen" VARCHAR NOT NULL ,"nombre" VARCHAR,"mapa" INTEGER NOT NULL ,"posx" INTEGER NOT NULL ,"posy" INTEGER NOT NULL ,"enemigo" BOOL NOT NULL ,"vida" INTEGER DEFAULT (1) );
CREATE TABLE "PESTATICO" ("id" INTEGER PRIMARY KEY  NOT NULL ,"imagen" VARCHAR NOT NULL ,"nombre" VARCHAR NOT NULL ,"mapa" INTEGER NOT NULL ,"posx" INTEGER NOT NULL ,"posy" INTEGER NOT NULL ,"vida" INTEGER DEFAULT (20) , "maxvida" INTEGER);
INSERT INTO MAPA (imagen) VALUES ('mp_a');
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (240, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (480, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (720, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (480, 144, 192, 144, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (768, 192, 192, 192, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (720, 240, 48, 96, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (672, 336, 192, 192, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (864, 336, 48, 96, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 672, 192, 48, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 480, 192, 192, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (192, 672, 192, 48, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (384, 432, 192, 192, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (384, 672, 192, 48, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (528, 384, 96, 96, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (576, 672, 192, 48, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (96, 192, 96, 96, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (768, 672, 192, 48, (SELECT id FROM MAPA WHERE imagen='mp_a'));
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_a1', (SELECT id FROM MAPA WHERE imagen='mp_a'), 336, 240, 1, 'mp_b1');
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_a_1a', (SELECT id FROM MAPA WHERE imagen='mp_a'), 528, 288, 1, 'mp_a_1b');
INSERT INTO MAPA (imagen) VALUES ('mp_a_a');
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (192, 0, 48, 96, (SELECT id FROM MAPA WHERE imagen='mp_a_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (240, 0, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_a_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 48, 96, 48, (SELECT id FROM MAPA WHERE imagen='mp_a_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (288, 0, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_a_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (96, 48, 96, 48, (SELECT id FROM MAPA WHERE imagen='mp_a_a'));
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_a_1b', (SELECT id FROM MAPA WHERE imagen='mp_a_a'), 48, 144, 3, 'mp_a_1a');
INSERT INTO MAPA (imagen) VALUES ('mp_b');
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (720, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (240, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (480, 0, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (48, 192, 240, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (288, 192, 240, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (528, 192, 240, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (48, 192, 48, 336, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 240, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (912, 240, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (96, 288, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (240, 336, 96, 189, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (528, 384, 144, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 432, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (912, 432, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (672, 480, 192, 144, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 624, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (912, 624, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (96, 624, 96, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (192, 720, 96, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 816, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (528, 672, 96, 288, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (912, 816, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (288, 816, 144, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (624, 816, 192, 144, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (48, 960, 144, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (816, 672, 96, 288, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 1008, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (864, 960, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (912, 1008, 48, 192, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (192, 1008, 144, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (624, 1008, 96, 189, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (768, 192, 48, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 1200, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (816, 192, 96, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (240, 1200, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (768, 240, 96, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (480, 1200, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (48, 768, 48, 96, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (720, 1200, 240, 240, (SELECT id FROM MAPA WHERE imagen='mp_b'));
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b1', (SELECT id FROM MAPA WHERE imagen='mp_b'), 336, 1152, 3, 'mp_a1');
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b_3a', (SELECT id FROM MAPA WHERE imagen='mp_b'), 144, 1056, 1, 'mp_b_3b');
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b_2a', (SELECT id FROM MAPA WHERE imagen='mp_b'), 576, 960, 1, 'mp_b_2b');
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b_1a', (SELECT id FROM MAPA WHERE imagen='mp_b'), 624, 288, 1, 'mp_b_1b');
INSERT INTO MAPA (imagen) VALUES ('mp_b_a');
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 0, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (336, 0, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (672, 0, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (144, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (192, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (672, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (432, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (480, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (528, 48, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_a'));
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b_1b', (SELECT id FROM MAPA WHERE imagen='mp_b_a'), 624, 48, 3, 'mp_b_1a');
INSERT INTO MAPA (imagen) VALUES ('mp_b_b');
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 0, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_b'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (288, 48, 48, 96, (SELECT id FROM MAPA WHERE imagen='mp_b_b'));
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b_2b', (SELECT id FROM MAPA WHERE imagen='mp_b_b'), 48, 192, 3, 'mp_b_2a');
INSERT INTO MAPA (imagen) VALUES ('mp_b_c');
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (48, 48, 96, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_c'));
INSERT INTO OBSTACULO (posx, posy, ancho, alto, mapa) VALUES (0, 96, 48, 48, (SELECT id FROM MAPA WHERE imagen='mp_b_c'));
INSERT INTO NEXO (id, mapa, posx, posy, direccion, enlace) VALUES ('mp_b_3b', (SELECT id FROM MAPA WHERE imagen='mp_b_c'), 192, 96, 3, 'mp_b_3a');
